apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-bedrock-config
  namespace: cloudacademy
  labels:
    app: fastapi-bedrock
data:
  # FastAPI Settings
  APP_NAME: "Bedrock Chat API"
  APP_VERSION: "1.0.0"
  DEBUG: "false"
  
  # CORS Settings
  CORS_ORIGINS: '["https://proyectos.cloudacademy.ar","http://localhost:3000"]'
  
  # AWS Cognito Settings
  COGNITO_REGION: "us-east-1"
  COGNITO_USER_POOL_ID: "us-east-1_kbBZ0w9sf"
  COGNITO_CLIENT_ID: "7ho22jco9j63c3hmsrsp4bj0ti"
  COGNITO_ISSUER: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_kbBZ0w9sf"
  
  # AWS Bedrock Settings
  BEDROCK_REGION: "us-east-1"
  BEDROCK_MODEL_ID: "anthropic.claude-3-haiku-20240307-v1:0"
  
  # Supported Courses
  SUPPORTED_COURSES: '["bedrock-rag","seguridad","networks","databases","devops"]'