name: Build and Deploy to S3
on:
  push:
    branches:
      - ft/auth2
    paths:
      - 'app/**'
      - 'lambda/**'
      - 'cloudfrontfunction/**'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install dependencies
        run: |
          cd app
          npm install
          
      - name: Build static site
        run: |
          cd app
          npm run build
          
      - name: Crear env.json
        run: |
          echo '{
            "cognitoUserPoolId": "us-east-1_S1fzr7edb",
            "cognitoUserPoolWebClientId": "5cn02jt88cf1q29d0sue55cuou"
          }' > ./app/out/env.json
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}
          
      - name: Deploy to S3
        run: aws s3 sync ./app/out s3://website-bucket-5d2io74t/ --delete
