name: Terraform Backend Apply

on:
  push:
    branches:
      - google-auth
    paths:
      - 'terraform/backend/**'
      - '.github/workflows/terraform-backend.yml'

jobs:
  terraform-backend-apply:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

      - name: Terraform Init
        working-directory: terraform/backend
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform/backend
        env:
          TF_VAR_google_client_id: ${{ secrets.GOOGLE_CLIENT_ID }}
          TF_VAR_google_client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          TF_VAR_production_callback_url: "https://proyectos.cloudacademy.ar"
          TF_VAR_production_logout_url: "https://proyectos.cloudacademy.ar"
        run: terraform apply -auto-approve 
